In [2]:
import pandas as pd
import numpy as np

In [3]:
np.random.seed(101)

In [5]:
arr = np.random.randint(1,100, (100,5))

In [7]:
df = pd.DataFrame(arr)
df

     0   1   2   3   4
0   20  70   2  78  64
1   88  29  71   6   4
2   13  63  27  97  62
3   88  75  98  65  96
4    4  89  60  39  30
..  ..  ..  ..  ..  ..
95  25  95  79  72  20
96  76  82  72  24  94
97  59  49  77  64  59
98  29  85  48  41  64
99  47  23   7  11  62

[100 rows x 5 columns]

In [23]:
df.columns = ['f1', 'f2', 'f3', 'f4', 'label']
df

    f1  f2  f3  f4  label
0   16  76  86  55     20
1   44  30  99  30     99
2   96  36  17  72     28
3   75  89  58  34     40
4   93  62  29  11     37
5   98  64  12  67     96
6   23  69  17  40     82
7   45   4  25  16     19
8   16  80  34  93     86
9   43  31  20  92     45
10  72  76  20  16     50
11  54  77  58  96     23
12  46  56  77  53     27
13  50  56  19  46     84
14  55  85  32  24      1
15  35   5  74  26     42
16  59  42  12  20      7
17  93  92  68  87     59
18  68  86  16  75     77
19  65  87  87  66     91
20  63  69  87  89     55
21  86  57  44  13     47
22  31  77  58  89     37
23  22  22  32  48     69
24  24  91   3  58     73
25  68  84  48  94     73
26  75  47  21  30      5
27  64  81  95  89     70
28  28  69  31  64     40
29  33  17  79  55      4
30  77  51  47  84     74
31  20  80  43  96     22
32  41  53  25  24     97
33  36  53  18  24     55
34  70  82  40  54     68
35  93  38  33  68     34
36  29  51  63  30     54
37  13  24  14  17      7
38  13  24  76  99     72
39   0  96  67  67     31
40   6  34  65  72     76
41  88  37  98  57     69
42  51  59  18  13     53
43  67  80  67  23     55
44  86  38   8  31     46
45  80  42   2  87     69
46  51  91  46  91     55
47  27  15   7  97      2
48  33  67  51  47     49
49   3  70   4  66      5

In [26]:
arr = np.random.randint(0,100, (50,4))
df = pd.DataFrame(arr, columns=['A', 'B', 'C', 'D'])

In [27]:
df

     A   B   C   D
0   39  20  45  19
1   14  22  97  67
2   76  73  85  59
3   38  71  12  77
4    2   6  38  24
5   27  54  49  68
6   23  74  41  81
7   71  24  63  52
8   81  25  56   7
9   41  16  42  11
10  25  21  74   6
11  25  20  63  60
12  89  68  88  39
13  75  77  59  37
14  16  82  64  82
15  51  11  64  44
16  80  83  79  84
17  29  36  83  71
18  34  37  40   4
19  99  88  89  34
20  71  64  44  89
21  14  70  12  54
22  49  18  88  60
23  96  56  93  68
24  53   6  67  24
25  99   0  67  93
26  47  15  72  68
27  60  91  80  83
28  11  44   6  58
29  50  34  39  71
30  26  91  59  89
31   0  86  14  91
32  47  74  23  42
33  48  26   4  66
34  43  84  30  79
35   9  78  49  28
36  89  34  93  41
37  21  88   2  86
38  84  25   2  50
39  49  63   2  95
40  28  21  62  50
41  99  52  56   5
42  42  82  75  22
43  34  48  60  72
44   9  95  96  46
45  59  51  47   4
46  59  36  34  98
47  81   8  95  60
48  46  19  13  35
49  14   6  24  31